"""
Pin-level design of the CAN-BUS FOC actuator carrier board (spin 1).

This is the electrical source of truth for the KiCad project: every component,
every pin, every net.  tools/gen_kicad.py renders it; tools/check_design.py
cross-checks it against hardware/bom/single_board_bom.csv.

Pin numbers come from verified sources, never from memory:
  * STM32G431CBTx, SN65HVD230, AMS1117-3.3 - KiCad official symbol libraries
    (/usr/share/kicad/symbols), which is also what the schematic references.
  * INA240A1D - KiCad upstream library symbol Amplifier_Current/INA240A1D:
        1 IN-   2 GND   3 REF2   4 GND   5 OUT   6 V+   7 REF1   8 IN+
    NOTE this is NOT the "1=IN+ ... 8=IN-" order that looks natural; pin 1 is
    the inverting input and pin 4 is a second GND.
  * SimpleFOC Mini H1/P1 - measured out of the module's own EasyEDA PCB file
    (SimpleFOCMini-1.0/EasyEDA/PCB_simplefocmini_2022-04-20.json).
"""

SHEET = dict(
    paper="A1",
    title="CAN-BUS FOC Actuator - carrier for SimpleFOC Mini",
    rev="A",
    company="f1133/CAN-BUS-FOC-Actuator",
    comment1="Spin 1: 12 V bus, DRV8313 power stage, 2-shunt inline INA240 sensing, CAN 1 Mbps",
    comment2="Generated by tools/gen_kicad.py from tools/board_design.py - edit those, not the .kicad_sch",
)

# Footprint shorthands
R1206 = "Resistor_SMD:R_1206_3216Metric"
C1206 = "Capacitor_SMD:C_1206_3216Metric"

# ---------------------------------------------------------------------------
# Components.  x/y are sheet millimetres, a = placement angle (0 = as drawn).
# pins maps pin NUMBER -> net name.  "" means intentionally unconnected
# (a no-connect flag is emitted).
# ---------------------------------------------------------------------------
C = []


def part(ref, lib_id, value, fp, x, y, pins, a=0, dnp=False, note=""):
    C.append(dict(ref=ref, lib_id=lib_id, value=value, fp=fp, x=x, y=y, a=a,
                  pins=pins, dnp=dnp, note=note))


def res(ref, value, x, y, pins, a=90, dnp=False, note=""):
    part(ref, "Device:R", value, R1206, x, y, pins, a, dnp, note)


def cap(ref, value, x, y, pins, a=0, dnp=False, note=""):
    part(ref, "Device:C", value, C1206, x, y, pins, a, dnp, note)


# ===== Block 1: power input, bulk, pass-through ============================
part("J1", "Connector_Generic:Conn_01x02", "12V IN",
     "Connector_JST:JST_VH_B2P-VH_1x02_P3.96mm_Vertical", 55, 45,
     {"1": "VBUS", "2": "GND"}, note="from the shared 12 V / 5 A PSU")
part("J13", "Connector_Generic:Conn_01x02", "12V OUT",
     "Connector_JST:JST_VH_B2P-VH_1x02_P3.96mm_Vertical", 55, 75,
     {"1": "VBUS", "2": "GND"}, note="daisy-chain to the next joint, >=2 mm trace")
part("J6", "Connector_Generic:Conn_01x02", "VM to Mini",
     "Connector_JST:JST_VH_B2P-VH_1x02_P3.96mm_Vertical", 55, 105,
     {"1": "VBUS", "2": "GND"}, note="wire W1 to the Mini screw terminal")
part("D1", "Device:D_TVS", "SMBJ15A", "Diode_SMD:D_SMB", 55, 135,
     {"1": "VBUS", "2": "GND"}, a=90, dnp=True, note="optional hot-plug clamp")
part("C3", "Device:C_Polarized", "470uF/50V", "Capacitor_SMD:CP_Elec_10x10.5", 55, 165,
     {"1": "VBUS", "2": "GND"})
part("C4", "Device:C_Polarized", "470uF/50V", "Capacitor_SMD:CP_Elec_10x10.5", 55, 195,
     {"1": "VBUS", "2": "GND"})
cap("C18", "100nF/250V", 55, 225, {"1": "VBUS", "2": "GND"}, note="HF at the J6 feed")
part("#FLG1", "power:PWR_FLAG", "PWR_FLAG", "", 90, 40, {"1": "VBUS"})
part("#FLG2", "power:PWR_FLAG", "PWR_FLAG", "", 115, 40, {"1": "GND"})

# ===== Block 2: 12 V -> AMS1117 -> 3V3 -> VDDA =============================
# No switcher. The LDO drops 8.7 V at ~100 mA = 0.87 W, which a SOT-223 can
# shed into a copper pour. That fixes the bus at 12 V: the AMS1117 is 18 V
# abs-max, and at 24 V it would burn 2.1 W. See hardware/calc/design_calcs.py.
cap("C5", "100nF/250V", 165, 70, {"1": "VBUS", "2": "GND"}, note="HF at the U8 input")
cap("C21", "10uF/25V", 165, 105, {"1": "VBUS", "2": "GND"},
    note="LDO input bulk; a 25 V X7R on a 12 V rail keeps roughly half its value")
part("U8", "Regulator_Linear:AMS1117-3.3", "AMS1117-3.3",
     "Package_TO_SOT_SMD:SOT-223-3_TabPin2", 165, 150,
     {"1": "GND", "2": "+3V3", "3": "VBUS"},
     note="12 V -> 3.3 V direct. Pour copper on the tab (pin 2 / VO)")
cap("C6", "10uF/25V", 165, 200, {"1": "+3V3", "2": "GND"}, note="LDO output stability: keep >= 10 uF")
cap("C7", "1uF/50V", 165, 230, {"1": "+3V3", "2": "GND"})
res("R23", "0R", 165, 265, {"1": "+3V3", "2": "VDDA"}, note="ferrite site")
cap("C11", "10uF/25V", 165, 295, {"1": "VDDA", "2": "GND"})
cap("C12", "100nF/250V", 165, 325, {"1": "VDDA", "2": "GND"})
cap("C13", "1uF/50V", 165, 355, {"1": "VDDA", "2": "GND"})

# ===== Block 3: MCU ========================================================
part("U1", "MCU_ST_STM32G4:STM32G431CBTx", "STM32G431CBT6",
     "Package_QFP:LQFP-48_7x7mm_P0.5mm", 320, 135, {
         "1": "+3V3",        # VBAT
         "2": "NODE_ID0",    # PC13
         "3": "NODE_ID1",    # PC14
         "4": "NODE_ID2",    # PC15
         "5": "XTAL_IN",     # PF0-OSC_IN
         "6": "XTAL_OUT",    # PF1-OSC_OUT
         "7": "NRST",        # PG10-NRST
         "8": "ISENSE_A",    # PA0  ADC1_IN1
         "9": "ISENSE_B",    # PA1  ADC2_IN2
         "10": "VBUS_SENSE", # PA2  ADC1_IN3
         "11": "TEMP_NTC",   # PA3  ADC1_IN4
         "12": "ENC_A_CS",   # PA4
         "13": "ENC_SCK",    # PA5  SPI1_SCK
         "14": "ENC_MISO",   # PA6  SPI1_MISO
         "15": "ENC_MOSI",   # PA7  SPI1_MOSI
         "16": "",           # PB0  spare (ADC1_IN15)
         "17": "",           # PB1  spare (ADC1_IN12)
         "18": "DRV_EN_MCU", # PB2
         "19": "GND",        # VSSA
         "20": "VDDA",       # VREF+
         "21": "VDDA",       # VDDA
         "22": "",           # PB10 spare
         "23": "GND",        # VSS
         "24": "+3V3",       # VDD
         "25": "",           # PB11 spare
         "26": "DRV_nFAULT", # PB12 TIM1_BKIN
         "27": "",           # PB13 spare
         "28": "DRV_nSLEEP", # PB14
         "29": "DRV_nRESET", # PB15
         "30": "PWM_A",      # PA8  TIM1_CH1
         "31": "PWM_B",      # PA9  TIM1_CH2
         "32": "PWM_C",      # PA10 TIM1_CH3
         "33": "CAN_RX",     # PA11 FDCAN1_RX
         "34": "CAN_TX",     # PA12 FDCAN1_TX
         "35": "GND",        # VSS
         "36": "+3V3",       # VDD
         "37": "SWDIO",      # PA13
         "38": "SWCLK",      # PA14
         "39": "ENC_B_CS",   # PA15
         "40": "UART_TX",    # PB3  USART2_TX
         "41": "UART_RX",    # PB4  USART2_RX
         "42": "",           # PB5  spare
         "43": "I2C_SCL",    # PB6  I2C1_SCL
         "44": "I2C_SDA",    # PB7  I2C1_SDA
         "45": "BOOT0",      # PB8  - BOOT0, nothing else may live here
         "46": "STATUS_LED", # PB9
         "47": "GND",        # VSS
         "48": "+3V3",       # VDD
     })

# ===== Block 4: MCU support ================================================
part("Y1", "Device:Crystal", "8MHz", "Crystal:Crystal_SMD_HC49-SD_HandSoldering", 450, 50,
     {"1": "XTAL_IN", "2": "XTAL_OUT"}, note="20 pF CL")
cap("C1", "30pF", 450, 85, {"1": "XTAL_IN", "2": "GND"})
cap("C2", "30pF", 450, 115, {"1": "XTAL_OUT", "2": "GND"})
cap("C8", "100nF/250V", 450, 150, {"1": "+3V3", "2": "GND"}, note="VDD pin 24")
cap("C9", "100nF/250V", 450, 180, {"1": "+3V3", "2": "GND"}, note="VDD pin 36")
cap("C10", "100nF/250V", 450, 210, {"1": "+3V3", "2": "GND"}, note="VDD pin 48")
cap("C22", "100nF/250V", 450, 240, {"1": "+3V3", "2": "GND"}, note="VBAT pin 1")
cap("C17", "100nF/250V", 450, 270, {"1": "NRST", "2": "GND"})
res("R1", "10k", 450, 300, {"1": "BOOT0", "2": "GND"}, note="BOOT0 must sit low at reset")
res("R3", "10k", 450, 335, {"1": "+3V3", "2": "TEMP_NTC"}, note="NTC bias")
res("R4", "10k", 450, 365, {"1": "VBUS", "2": "VBUS_DIV_MID"})
res("R5", "10k", 450, 395, {"1": "VBUS_DIV_MID", "2": "VBUS_SENSE"})
res("R6", "2.2k", 450, 425, {"1": "VBUS_SENSE", "2": "GND"}, note="24 V -> 2.38 V")

# ===== Block 5: debug, LEDs, node ID =======================================
part("J11", "Connector_Generic:Conn_01x04", "SWD",
     "Connector_PinHeader_2.54mm:PinHeader_1x04_P2.54mm_Vertical", 560, 55,
     {"1": "+3V3", "2": "SWDIO", "3": "SWCLK", "4": "GND"})
part("J12", "Connector_Generic:Conn_01x03", "UART",
     "Connector_PinHeader_2.54mm:PinHeader_1x03_P2.54mm_Vertical", 560, 100,
     {"1": "UART_TX", "2": "UART_RX", "3": "GND"})
res("R9", "2.2k", 560, 140, {"1": "+3V3", "2": "LED1_A"})
part("LED1", "Device:LED", "PWR", "LED_SMD:LED_1206_3216Metric", 560, 170,
     {"2": "LED1_A", "1": "GND"}, a=90)
res("R10", "2.2k", 560, 205, {"1": "STATUS_LED", "2": "LED2_A"})
part("LED2", "Device:LED", "STATUS", "LED_SMD:LED_1206_3216Metric", 560, 235,
     {"2": "LED2_A", "1": "GND"}, a=90)
res("R11", "2.2k", 560, 275, {"1": "NODE_ID0", "2": "GND"})
res("R12", "2.2k", 560, 305, {"1": "NODE_ID1", "2": "GND"})
res("R13", "2.2k", 560, 335, {"1": "NODE_ID2", "2": "GND"})
res("R17", "0R", 560, 370, {"1": "+3V3", "2": "NODE_ID0"}, dnp=True, note="strap = bit 0 set")
res("R18", "0R", 560, 400, {"1": "+3V3", "2": "NODE_ID1"}, dnp=True, note="strap = bit 1 set")
res("R19", "0R", 560, 430, {"1": "+3V3", "2": "NODE_ID2"}, dnp=True, note="strap = bit 2 set")

# ===== Block 6: SimpleFOC Mini socket ======================================
part("U6", "canfoc:SimpleFOC_Mini", "SimpleFOC Mini", "canfoc:SimpleFOC_Mini_Socket", 665, 120, {
    "1": "GND",          # H1.1
    "2": "",             # H1.2 3.3V-out from the DRV8313 LDO - MUST stay unconnected
    "3": "PWM_A",        # H1.3 IN1
    "4": "GND",          # H1.4
    "5": "PWM_B",        # H1.5 IN2
    "6": "DRV_nRESET",   # H1.6
    "7": "PWM_C",        # H1.7 IN3
    "8": "DRV_nSLEEP",   # H1.8
    "9": "DRV_EN",       # H1.9
    "10": "DRV_nFAULT",  # H1.10
    "11": "PH_C",        # P1.1 OUT3
    "12": "PH_B_DRV",    # P1.2 OUT2
    "13": "PH_A_DRV",    # P1.3 OUT1
})
res("R2", "10k", 665, 195, {"1": "DRV_EN", "2": "GND"}, note="bridge off through reset")
res("R20", "0R", 665, 230, {"1": "DRV_EN_MCU", "2": "DRV_EN"}, note="bridge-disable jumper")

# ===== Block 7: inline current sense =======================================
# ERJ8CWFR030V is a two-terminal 1206 part: Device:R_Shunt's 4-pin Kelvin symbol
# would not match its 2-pad footprint. The Kelvin connection is a layout rule -
# U3/U4 IN+/IN- leave from the inner edge of the shunt pads, not the current path.
part("RS1", "Device:R", "30mR/1W", R1206, 760, 60,
     {"1": "PH_A_DRV", "2": "PH_A_MOT"}, a=90, note="ERJ8CWFR030V, Kelvin taps to U3")
part("RS2", "Device:R", "30mR/1W", R1206, 760, 90,
     {"1": "PH_B_DRV", "2": "PH_B_MOT"}, a=90, note="ERJ8CWFR030V, Kelvin taps to U4")
part("U3", "canfoc:INA240A1D", "INA240A1D", "Package_SO:SOIC-8_3.9x4.9mm_P1.27mm", 760, 150, {
    "8": "PH_A_DRV",   # IN+  Mini side  -> positive reading = current into the motor
    "1": "PH_A_MOT",   # IN-  motor side
    "2": "GND", "4": "GND",
    "3": "GND",        # REF2
    "7": "+3V3",       # REF1  -> output biased to VS/2 = 1.65 V
    "6": "+3V3",       # V+
    "5": "ISENSE_A_RAW",
})
cap("C14", "100nF/250V", 760, 200, {"1": "+3V3", "2": "GND"}, note="U3 VS")
part("U4", "canfoc:INA240A1D", "INA240A1D", "Package_SO:SOIC-8_3.9x4.9mm_P1.27mm", 760, 245, {
    "8": "PH_B_DRV", "1": "PH_B_MOT",
    "2": "GND", "4": "GND", "3": "GND", "7": "+3V3", "6": "+3V3",
    "5": "ISENSE_B_RAW",
})
cap("C15", "100nF/250V", 760, 295, {"1": "+3V3", "2": "GND"}, note="U4 VS")
res("R21", "0R", 760, 330, {"1": "ISENSE_A_RAW", "2": "ISENSE_A"}, note="RC site: 10R later")
res("R22", "0R", 760, 360, {"1": "ISENSE_B_RAW", "2": "ISENSE_B"}, note="RC site: 10R later")
cap("C19", "1nF", 760, 395, {"1": "ISENSE_A", "2": "GND"}, dnp=True)
cap("C20", "1nF", 760, 425, {"1": "ISENSE_B", "2": "GND"}, dnp=True)
part("J2", "Connector_Generic:Conn_01x03", "MOTOR",
     "Connector_JST:JST_XH_B3B-XH-A_1x03_P2.50mm_Vertical", 665, 300,
     {"1": "PH_A_MOT", "2": "PH_B_MOT", "3": "PH_C"})

# ===== Block 8: CAN ========================================================
part("U2", "Interface_CAN_LIN:SN65HVD230", "SN65HVD230",
     "Package_SO:SOIC-8_3.9x4.9mm_P1.27mm", 55, 300,
     {"1": "CAN_TX", "2": "GND", "3": "+3V3", "4": "CAN_RX",
      "5": "", "6": "CANL", "7": "CANH", "8": "CAN_RS"},
     note="TCAN332 drops into the same footprint for 5 Mbps FD")
cap("C16", "100nF/250V", 55, 350, {"1": "+3V3", "2": "GND"})
res("R16", "0R", 55, 385, {"1": "CAN_RS", "2": "GND"}, note="high-speed mode")
res("R15", "0R", 55, 415, {"1": "CANH", "2": "TERM_MID"}, dnp=True, note="termination select")
res("R14", "120R", 55, 445, {"1": "TERM_MID", "2": "CANL"}, dnp=True, note="end boards only")
part("J9", "Connector_Generic:Conn_01x03", "CAN IN",
     "Connector_JST:JST_XH_B3B-XH-A_1x03_P2.50mm_Vertical", 55, 485,
     {"1": "CANH", "2": "CANL", "3": "GND"})
part("J10", "Connector_Generic:Conn_01x03", "CAN OUT",
     "Connector_JST:JST_XH_B3B-XH-A_1x03_P2.50mm_Vertical", 55, 525,
     {"1": "CANH", "2": "CANL", "3": "GND"})

# ===== Block 9: encoder / sensor connectors ================================
part("J3", "Connector_Generic:Conn_01x05", "AS5600 + NTC",
     "Connector_JST:JST_XH_B5B-XH-A_1x05_P2.50mm_Vertical", 165, 470,
     {"1": "+3V3", "2": "GND", "3": "I2C_SCL", "4": "I2C_SDA", "5": "TEMP_NTC"})
res("R7", "4.7k", 165, 525, {"1": "+3V3", "2": "I2C_SCL"}, dnp=True, note="DNP if on the AS5600 board")
res("R8", "4.7k", 165, 555, {"1": "+3V3", "2": "I2C_SDA"}, dnp=True)
part("J4", "Connector_Generic:Conn_01x06", "SPI_A motor side",
     "Connector_PinHeader_2.54mm:PinHeader_1x06_P2.54mm_Vertical", 320, 470,
     {"1": "+3V3", "2": "GND", "3": "ENC_A_CS", "4": "ENC_SCK", "5": "ENC_MISO", "6": "ENC_MOSI"})
part("J5", "Connector_Generic:Conn_01x06", "SPI_B output side",
     "Connector_PinHeader_2.54mm:PinHeader_1x06_P2.54mm_Vertical", 450, 470,
     {"1": "+3V3", "2": "GND", "3": "ENC_B_CS", "4": "ENC_SCK", "5": "ENC_MISO", "6": "ENC_MOSI"})

# ===== Mechanical ==========================================================
for i, (mx, my) in enumerate([(640, 470), (680, 470), (720, 470), (760, 470), (800, 470)], 1):
    part(f"MH{i}", "Mechanical:MountingHole", "M3", "MountingHole:MountingHole_3.2mm_M3", mx, my, {})

# ---------------------------------------------------------------------------
# Block titles drawn on the sheet
# ---------------------------------------------------------------------------
BLOCKS = [
    ("12 V INPUT, BULK, PASS-THROUGH", 30, 28),
    ("CAN 1 Mbps", 30, 283),
    ("LOGIC RAIL   12 V -> AMS1117 -> 3V3 -> VDDA", 140, 28),
    ("ENCODER / SENSOR CONNECTORS", 140, 452),
    ("MCU", 275, 28),
    ("MCU SUPPORT, VBUS DIVIDER, NTC", 425, 28),
    ("DEBUG, LEDS, CAN NODE ID", 535, 28),
    ("POWER STAGE - SimpleFOC Mini (DRV8313)", 615, 28),
    ("INLINE CURRENT SENSE", 735, 28),
    ("MOUNTING", 615, 452),
]

NOTES = [
    (615, 268, "U6 pin 2 is the DRV8313's 3.3 V LDO output (30 mA). It is deliberately"),
    (615, 274, "left unconnected - it must never be paralleled with the carrier 3V3 rail."),
    (735, 445, "RS1/RS2 are Kelvin-sensed: U3/U4 IN+/IN- leave from the inner edge of the"),
    (735, 451, "shunt pads. IN+ is the Mini side, so positive current reads above 1.65 V."),
    (425, 452, "Spare MCU pins PB0 PB1 PB5 PB10 PB11 PB13 are flagged no-connect;"),
    (425, 458, "they are the expansion for a spin-2 discrete bridge (see docs/06)."),
]
